# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

baseURL = "https://vrm-addon-for-blender.info"
defaultContentLanguage = "en"

enableEmoji = true
enableRobotsTXT = true
summaryLength = 0

defaultContentLanguageInSubdir = true
googleAnalytics = 'G-L4E126M2JR'

[languages]

[languages.en]
  title = 'VRM Add-on for Blender'

[languages.ja]
  title = 'VRM Add-on for Blender'

[languages.en.params]
  isoCode = 'en'

[languages.ja.params]
  isoCode = 'ja'

[[languages.en.menu.main]]
  name = "Download"
  url = "https://vrm-addon-for-blender.info/releases/VRM_Addon_for_Blender-release.zip"

[[languages.en.menu.main]]
  name = "Report Bugs"
  url = "https://github.com/saturday06/VRM-Addon-for-Blender/issues"

[[languages.ja.menu.main]]
  name = "ダウンロード"
  url = "https://vrm-addon-for-blender.info/releases/VRM_Addon_for_Blender-release.zip"

[[languages.ja.menu.main]]
  name = "バグを報告"
  url = "https://github.com/saturday06/VRM-Addon-for-Blender/issues"

[author]
  # name = "author"
  # image = "images/author.jpg"
  # bio = "A little bit about you"
  links = [
  #   { email = "mailto:hello@your_domain.com" },
  #   { link = "https://link-to-some-website.com/" },
  #   { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
  #   { apple = "https://www.apple.com" },
  #   { codepen = "https://codepen.io/username" },
  #   { dev = "https://dev.to/username" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { facebook = "https://facebook.com/username" },
  #   { flickr = "https://www.flickr.com/photos/username/" },
  #   { foursquare = "https://foursquare.com/username" },
  #    { github = "https://github.com/username" },
  #   { gitlab = "https://gitlab.com/username" },
  #   { google = "https://www.google.com/" },
  #   { instagram = "https://instagram.com/username" },
  #   { keybase = "https://keybase.io/username" },
  #   { kickstarter = "https://www.kickstarter.com/profile/username" },
  #   { lastfm = "https://lastfm.com/user/username" },
  #   { linkedin = "https://linkedin.com/in/username" },
  #   { mastodon = "https://mastodon.instance/@username" },
  #   { medium = "https://medium.com/username" },
  #   { microsoft = "https://www.microsoft.com/" },
  #   { patreon = "https://www.patreon.com/username" },
  #   { pinterest = "https://pinterest.com/username" },
  #   { reddit = "https://reddit.com/user/username" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { snapchat = "https://snapchat.com/add/username" },
  #   { soundcloud = "https://soundcloud.com/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { twitter = "https://twitter.com/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
  ]
