name: pages-update

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          set -x

          if ! curl \
            --fail \
            --retry 20 \
            --retry-all-errors \
            --show-error \
            --location \
            --output releases_latest.json \
            --header "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest; then

            if [ "$GITHUB_REPOSITORY_OWNER" != "saturday06" ]; then
              exit 0
            fi
            exit 1
          fi

          HUGO_VRM_ADDON_FOR_BLENDER_LATEST_VERSION_NAME=$(ruby -rjson -e "puts JSON.parse(File.read('releases_latest.json'))['name']")
          export HUGO_VRM_ADDON_FOR_BLENDER_LATEST_VERSION_NAME
          HUGO_VRM_ADDON_FOR_BLENDER_LATEST_PUBLISH_DATE=$(ruby -rjson -e "puts JSON.parse(File.read('releases_latest.json'))['published_at']")
          export HUGO_VRM_ADDON_FOR_BLENDER_LATEST_PUBLISH_DATE

          hugo_dir=$(mktemp -d)

          pushd "$hugo_dir"
            curl \
              --fail \
              --retry 20 \
              --retry-all-errors \
              --show-error \
              --location \
              --output hugo_extended.tar.gz \
              --header "Accept: application/vnd.github.v3+json" \
              https://github.com/gohugoio/hugo/releases/download/v0.111.3/hugo_extended_0.111.3_Linux-64bit.tar.gz
            tar xf hugo_extended.tar.gz
          popd

          git fetch --depth=1 origin gh-pages
          cd docs/website
          mkdir public
          pushd public
            cp -fr ../../../.git .git
            git checkout gh-pages
          popd

          "$hugo_dir/hugo" --minify

      - name: Deploy
        run: |
          set -x

          git fetch --depth=1 origin main website
          case "$GITHUB_SHA" in
            "$(git rev-parse origin/main)");;
            "$(git rev-parse origin/website)");;
            *) exit 0;;
          esac

          cd docs/website/public
          git add .
          if git diff --cached --exit-code; then
            exit 0
          fi
          git config --global user.email "isamu@leafytree.jp"
          git config --global user.name "[BOT] Isamu Mogi"
          git commit -m "docs: update to $GITHUB_SHA [BOT]"
          git push origin gh-pages
