ARKIT = {
    'Data': {
        'eyeBlinkLeft': {'index': 0, 'name': 'eyeBlinkLeft'},
        'eyeLookDownLeft': {'index': 1, 'name': 'eyeLookDownLeft'},
        'eyeLookInLeft': {'index': 2, 'name': 'eyeLookInLeft'},
        'eyeLookOutLeft': {'index': 3, 'name': 'eyeLookOutLeft'},
        'eyeLookUpLeft': {'index': 4, 'name': 'eyeLookUpLeft'},
        'eyeSquintLeft': {'index': 5, 'name': 'eyeSquintLeft'},
        'eyeWideLeft': {'index': 6, 'name': 'eyeWideLeft'},
        'eyeBlinkRight': {'index': 7, 'name': 'eyeBlinkRight'},
        'eyeLookDownRight': {'index': 8, 'name': 'eyeLookDownRight'},
        'eyeLookInRight': {'index': 9, 'name': 'eyeLookInRight'},
        'eyeLookOutRight': {'index': 10, 'name': 'eyeLookOutRight'},
        'eyeLookUpRight': {'index': 11, 'name': 'eyeLookUpRight'},
        'eyeSquintRight': {'index': 12, 'name': 'eyeSquintRight'},
        'eyeWideRight': {'index': 13, 'name': 'eyeWideRight'},
        'jawForward': {'index': 14, 'name': 'jawForward'},
        'jawLeft': {'index': 15, 'name': 'jawLeft'},
        'jawRight': {'index': 16, 'name': 'jawRight'},
        'jawOpen': {'index': 17, 'name': 'jawOpen'},
        'mouthClose': {'index': 18, 'name': 'mouthClose'},
        'mouthFunnel': {'index': 19, 'name': 'mouthFunnel'},
        'mouthPucker': {'index': 20, 'name': 'mouthPucker'},
        'mouthRight': {'index': 21, 'name': 'mouthRight'},
        'mouthLeft': {'index': 22, 'name': 'mouthLeft'},
        'mouthSmileLeft': {'index': 23, 'name': 'mouthSmileLeft'},
        'mouthSmileRight': {'index': 24, 'name': 'mouthSmileRight'},
        'mouthFrownRight': {'index': 25, 'name': 'mouthFrownRight'},
        'mouthFrownLeft': {'index': 26, 'name': 'mouthFrownLeft'},
        'mouthDimpleLeft': {'index': 27, 'name': 'mouthDimpleLeft'},
        'mouthDimpleRight': {'index': 28, 'name': 'mouthDimpleRight'},
        'mouthStretchLeft': {'index': 29, 'name': 'mouthStretchLeft'},
        'mouthStretchRight': {'index': 30, 'name': 'mouthStretchRight'},
        'mouthRollLower': {'index': 31, 'name': 'mouthRollLower'},
        'mouthRollUpper': {'index': 32, 'name': 'mouthRollUpper'},
        'mouthShrugLower': {'index': 33, 'name': 'mouthShrugLower'},
        'mouthShrugUpper': {'index': 34, 'name': 'mouthShrugUpper'},
        'mouthPressLeft': {'index': 35, 'name': 'mouthPressLeft'},
        'mouthPressRight': {'index': 36, 'name': 'mouthPressRight'},
        'mouthLowerDownLeft': {'index': 37, 'name': 'mouthLowerDownLeft'},
        'mouthLowerDownRight': {'index': 38, 'name': 'mouthLowerDownRight'},
        'mouthUpperUpLeft': {'index': 39, 'name': 'mouthUpperUpLeft'},
        'mouthUpperUpRight': {'index': 40, 'name': 'mouthUpperUpRight'},
        'browDownLeft': {'index': 41, 'name': 'browDownLeft'},
        'browDownRight': {'index': 42, 'name': 'browDownRight'},
        'browInnerUp': {'index': 43, 'name': 'browInnerUp'},
        'browOuterUpLeft': {'index': 44, 'name': 'browOuterUpLeft'},
        'browOuterUpRight': {'index': 45, 'name': 'browOuterUpRight'},
        'cheekPuff': {'index': 46, 'name': 'cheekPuff'},
        'cheekSquintLeft': {'index': 47, 'name': 'cheekSquintLeft'},
        'cheekSquintRight': {'index': 48, 'name': 'cheekSquintRight'},
        'noseSneerLeft': {'index': 49, 'name': 'noseSneerLeft'},
        'noseSneerRight': {'index': 50, 'name': 'noseSneerRight'},
        'tongueOut': {'index': 51, 'name': 'tongueOut'},
    }
}
FACECAP = {
    'Data': {
        'browInnerUp': {'index': 0, 'name': 'browInnerUp'},
        'browDownLeft': {'index': 1, 'name': 'browDown_L'},
        'browDownRight': {'index': 2, 'name': 'browDown_R'},
        'browOuterUpLeft': {'index': 3, 'name': 'browOuterUp_L'},
        'browOuterUpRight': {'index': 4, 'name': 'browOuterUp_R'},
        'eyeLookUpLeft': {'index': 5, 'name': 'eyeLookUp_L'},
        'eyeLookUpRight': {'index': 6, 'name': 'eyeLookUp_R'},
        'eyeLookDownLeft': {'index': 7, 'name': 'eyeLookDown_L'},
        'eyeLookDownRight': {'index': 8, 'name': 'eyeLookDown_R'},
        'eyeLookInLeft': {'index': 9, 'name': 'eyeLookIn_L'},
        'eyeLookInRight': {'index': 10, 'name': 'eyeLookIn_R'},
        'eyeLookOutLeft': {'index': 11, 'name': 'eyeLookOut_L'},
        'eyeLookOutRight': {'index': 12, 'name': 'eyeLookOut_R'},
        'eyeBlinkLeft': {'index': 13, 'name': 'eyeBlink_L'},
        'eyeBlinkRight': {'index': 14, 'name': 'eyeBlink_R'},
        'eyeSquintLeft': {'index': 15, 'name': 'eyeSquint_L'},
        'eyeSquintRight': {'index': 16, 'name': 'eyeSquint_R'},
        'eyeWideLeft': {'index': 17, 'name': 'eyeWide_L'},
        'eyeWideRight': {'index': 18, 'name': 'eyeWide_R'},
        'cheekPuff': {'index': 19, 'name': 'cheekPuff'},
        'cheekSquintLeft': {'index': 20, 'name': 'cheekSquint_L'},
        'cheekSquintRight': {'index': 21, 'name': 'cheekSquint_R'},
        'noseSneerLeft': {'index': 22, 'name': 'noseSneer_L'},
        'noseSneerRight': {'index': 23, 'name': 'noseSneer_R'},
        'jawOpen': {'index': 24, 'name': 'jawOpen'},
        'jawForward': {'index': 25, 'name': 'jawForward'},
        'jawLeft': {'index': 26, 'name': 'jawLeft'},
        'jawRight': {'index': 27, 'name': 'jawRight'},
        'mouthFunnel': {'index': 28, 'name': 'mouthFunnel'},
        'mouthPucker': {'index': 29, 'name': 'mouthPucker'},
        'mouthLeft': {'index': 30, 'name': 'mouthLeft'},
        'mouthRight': {'index': 31, 'name': 'mouthRight'},
        'mouthRollUpper': {'index': 32, 'name': 'mouthRollUpper'},
        'mouthRollLower': {'index': 33, 'name': 'mouthRollLower'},
        'mouthShrugUpper': {'index': 34, 'name': 'mouthShrugUpper'},
        'mouthShrugLower': {'index': 35, 'name': 'mouthShrugLower'},
        'mouthClose': {'index': 36, 'name': 'mouthClose'},
        'mouthSmileLeft': {'index': 37, 'name': 'mouthSmile_L'},
        'mouthSmileRight': {'index': 38, 'name': 'mouthSmile_R'},
        'mouthFrownLeft': {'index': 39, 'name': 'mouthFrown_L'},
        'mouthFrownRight': {'index': 40, 'name': 'mouthFrown_R'},
        'mouthDimpleLeft': {'index': 41, 'name': 'mouthDimple_L'},
        'mouthDimpleRight': {'index': 42, 'name': 'mouthDimple_R'},
        'mouthUpperUpLeft': {'index': 43, 'name': 'mouthUpperUp_L'},
        'mouthUpperUpRight': {'index': 44, 'name': 'mouthUpperUp_R'},
        'mouthLowerDownLeft': {'index': 45, 'name': 'mouthLowerDown_L'},
        'mouthLowerDownRight': {'index': 46, 'name': 'mouthLowerDown_R'},
        'mouthPressLeft': {'index': 47, 'name': 'mouthPress_L'},
        'mouthPressRight': {'index': 48, 'name': 'mouthPress_R'},
        'mouthStretchLeft': {'index': 49, 'name': 'mouthStretch_L'},
        'mouthStretchRight': {'index': 50, 'name': 'mouthStretch_R'},
        'tongueOut': {'index': 51, 'name': 'tongueOut'},
    },
}
EPIC = {
    'Data': {
        'eyeBlinkRight': {'index': 0, 'name': 'eyeBlinkRight'},
        'eyeLookDownRight': {'index': 1, 'name': 'eyeLookDownRight'},
        'eyeLookInRight': {'index': 2, 'name': 'eyeLookInRight'},
        'eyeLookOutRight': {'index': 3, 'name': 'eyeLookOutRight'},
        'eyeLookUpRight': {'index': 4, 'name': 'eyeLookUpRight'},
        'eyeSquintRight': {'index': 5, 'name': 'eyeSquintRight'},
        'eyeWideRight': {'index': 6, 'name': 'eyeWideRight'},
        'eyeBlinkLeft': {'index': 7, 'name': 'eyeBlinkLeft'},
        'eyeLookDownLeft': {'index': 8, 'name': 'eyeLookDownLeft'},
        'eyeLookInLeft': {'index': 9, 'name': 'eyeLookInLeft'},
        'eyeLookOutLeft': {'index': 10, 'name': 'eyeLookOutLeft'},
        'eyeLookUpLeft': {'index': 11, 'name': 'eyeLookUpLeft'},
        'eyeSquintLeft': {'index': 12, 'name': 'eyeSquintLeft'},
        'eyeWideLeft': {'index': 13, 'name': 'eyeWideLeft'},
        'jawForward': {'index': 14, 'name': 'jawForward'},
        'jawRight': {'index': 15, 'name': 'jawRight'},
        'jawLeft': {'index': 16, 'name': 'jawLeft'},
        'jawOpen': {'index': 17, 'name': 'jawOpen'},
        'mouthClose': {'index': 18, 'name': 'mouthClose'},
        'mouthFunnel': {'index': 19, 'name': 'mouthFunnel'},
        'mouthPucker': {'index': 20, 'name': 'mouthPucker'},
        'mouthRight': {'index': 21, 'name': 'mouthRight'},
        'mouthLeft': {'index': 22, 'name': 'mouthLeft'},
        'mouthSmileRight': {'index': 23, 'name': 'mouthSmileRight'},
        'mouthSmileLeft': {'index': 24, 'name': 'mouthSmileLeft'},
        'mouthFrownRight': {'index': 25, 'name': 'mouthFrownRight'},
        'mouthFrownLeft': {'index': 26, 'name': 'mouthFrownLeft'},
        'mouthDimpleRight': {'index': 27, 'name': 'mouthDimpleRight'},
        'mouthDimpleLeft': {'index': 28, 'name': 'mouthDimpleLeft'},
        'mouthStretchRight': {'index': 29, 'name': 'mouthStretchRight'},
        'mouthStretchLeft': {'index': 30, 'name': 'mouthStretchLeft'},
        'mouthRollLower': {'index': 31, 'name': 'mouthRollLower'},
        'mouthRollUpper': {'index': 32, 'name': 'mouthRollUpper'},
        'mouthShrugLower': {'index': 33, 'name': 'mouthShrugLower'},
        'mouthShrugUpper': {'index': 34, 'name': 'mouthShrugUpper'},
        'mouthPressRight': {'index': 35, 'name': 'mouthPressRight'},
        'mouthPressLeft': {'index': 36, 'name': 'mouthPressLeft'},
        'mouthLowerDownRight': {'index': 37, 'name': 'mouthLowerDownRight'},
        'mouthLowerDownLeft': {'index': 38, 'name': 'mouthLowerDownLeft'},
        'mouthUpperUpRight': {'index': 39, 'name': 'mouthUpperUpRight'},
        'mouthUpperUpLeft': {'index': 40, 'name': 'mouthUpperUpLeft'},
        'browDownRight': {'index': 41, 'name': 'browDownRight'},
        'browDownLeft': {'index': 42, 'name': 'browDownLeft'},
        'browInnerUp': {'index': 43, 'name': 'browInnerUp'},
        'browOuterUpRight': {'index': 44, 'name': 'browOuterUpRight'},
        'browOuterUpLeft': {'index': 45, 'name': 'browOuterUpLeft'},
        'cheekPuff': {'index': 46, 'name': 'cheekPuff'},
        'cheekSquintRight': {'index': 47, 'name': 'cheekSquintRight'},
        'cheekSquintLeft': {'index': 48, 'name': 'cheekSquintLeft'},
        'noseSneerRight': {'index': 49, 'name': 'noseSneerRight'},
        'noseSneerLeft': {'index': 50, 'name': 'noseSneerLeft'},
        'tongueOut': {'index': 51, 'name': 'tongueOut'},
    },
}
A2F = {
    'Data': {
        'browLowerL': {'index': 0, 'name': 'browLowerL'},
        'browLowerR': {'index': 1, 'name': 'browLowerR'},
        'innerBrowRaiserL': {'index': 2, 'name': 'innerBrowRaiserL'},
        'innerBrowRaiserR': {'index': 3, 'name': 'innerBrowRaiserR'},
        'outerBrowRaiserL': {'index': 4, 'name': 'outerBrowRaiserL'},
        'outerBrowRaiserR': {'index': 5, 'name': 'outerBrowRaiserR'},
        'eyesLookLeft': {'index': 6, 'name': 'eyesLookLeft'},
        'eyesLookRight': {'index': 7, 'name': 'eyesLookRight'},
        'eyesLookUp': {'index': 8, 'name': 'eyesLookUp'},
        'eyesLookDown': {'index': 9, 'name': 'eyesLookDown'},
        'eyesCloseL': {'index': 10, 'name': 'eyesCloseL'},
        'eyesCloseR': {'index': 11, 'name': 'eyesCloseR'},
        'eyesUpperLidRaiserL': {'index': 12, 'name': 'eyesUpperLidRaiserL'},
        'eyesUpperLidRaiserR': {'index': 13, 'name': 'eyesUpperLidRaiserR'},
        'squintL': {'index': 14, 'name': 'squintL'},
        'squintR': {'index': 15, 'name': 'squintR'},
        'cheekRaiserL': {'index': 16, 'name': 'cheekRaiserL'},
        'cheekRaiserR': {'index': 17, 'name': 'cheekRaiserR'},
        'cheekPuffL': {'index': 18, 'name': 'cheekPuffL'},
        'cheekPuffR': {'index': 19, 'name': 'cheekPuffR'},
        'noseWrinklerL': {'index': 20, 'name': 'noseWrinklerL'},
        'noseWrinklerR': {'index': 21, 'name': 'noseWrinklerR'},
        'jawDrop': {'index': 22, 'name': 'jawDrop'},
        'jawDropLipTowards': {'index': 23, 'name': 'jawDropLipTowards'},
        'jawThrust': {'index': 24, 'name': 'jawThrust'},
        'jawSlideLeft': {'index': 25, 'name': 'jawSlideLeft'},
        'jawSlideRight': {'index': 26, 'name': 'jawSlideRight'},
        'mouthSlideLeft': {'index': 27, 'name': 'mouthSlideLeft'},
        'mouthSlideRight': {'index': 28, 'name': 'mouthSlideRight'},
        'dimplerL': {'index': 29, 'name': 'dimplerL'},
        'dimplerR': {'index': 30, 'name': 'dimplerR'},
        'lipCornerPullerL': {'index': 31, 'name': 'lipCornerPullerL'},
        'lipCornerPullerR': {'index': 32, 'name': 'lipCornerPullerR'},
        'lipCornerDepressorL': {'index': 33, 'name': 'lipCornerDepressorL'},
        'lipCornerDepressorR': {'index': 34, 'name': 'lipCornerDepressorR'},
        'lipStretcherL': {'index': 35, 'name': 'lipStretcherL'},
        'lipStretcherR': {'index': 36, 'name': 'lipStretcherR'},
        'upperLipRaiserL': {'index': 37, 'name': 'upperLipRaiserL'},
        'upperLipRaiserR': {'index': 38, 'name': 'upperLipRaiserR'},
        'lowerLipDepressorL': {'index': 39, 'name': 'lowerLipDepressorL'},
        'lowerLipDepressorR': {'index': 40, 'name': 'lowerLipDepressorR'},
        'chinRaiser': {'index': 41, 'name': 'chinRaiser'},
        'lipPressor': {'index': 42, 'name': 'lipPressor'},
        'pucker': {'index': 43, 'name': 'pucker'},
        'funneler': {'index': 44, 'name': 'funneler'},
        'lipSuck': {'index': 45, 'name': 'lipSuck'}
    },
}

PHONEMES = {
    'Data': {
        'aa_ah_ax_01': {'index': 0, 'name': 'aa_ah_ax_01'},
        'aa_02': {'index': 1, 'name': 'aa_02'},
        'ao_03': {'index': 2, 'name': 'ao_03'},
        'ey_eh_uh_04': {'index': 3, 'name': 'ey_eh_uh_04'},
        'er_05': {'index': 4, 'name': 'er_05'},
        'y_iy_ih_ix_06': {'index': 5, 'name': 'y_iy_ih_ix_06'},
        'w_uw_07': {'index': 6, 'name': 'w_uw_07'},
        'ow_08': {'index': 7, 'name': 'ow_08'},
        'aw_09': {'index': 8, 'name': 'aw_09'},
        'oy_10': {'index': 9, 'name': 'oy_10'},
        'ay_11': {'index': 10, 'name': 'ay_11'},
        'h_12': {'index': 11, 'name': 'h_12'},
        'r_13': {'index': 12, 'name': 'r_13'},
        'l_14': {'index': 13, 'name': 'l_14'},
        's_z_15': {'index': 14, 'name': 's_z_15'},
        'sh_ch_jh_zh_16': {'index': 15, 'name': 'sh_ch_jh_zh_16'},
        'th_dh_17': {'index': 16, 'name': 'th_dh_17'},
        'f_v_18': {'index': 17, 'name': 'f_v_18'},
        'd_t_n_19': {'index': 18, 'name': 'd_t_n_19'},
        'k_g_ng_20': {'index': 19, 'name': 'k_g_ng_20'},
        'p_b_m_21': {'index': 20, 'name': 'p_b_m_21'},
    }
}


TONGUE = {
    'Data': {
        'tongueOut': {'index': 0, 'name': 'tongueOut'},
        'tongueUp': {'index': 1, 'name': 'tongueUp'},
        'tongueBack': {'index': 2, 'name': 'tongueBack'},
        'tongueTwistLeft': {'index': 3, 'name': 'tongueTwistLeft'},
        'tongueTwistRight': {'index': 4, 'name': 'tongueTwistRight'},
        'tongueLeft': {'index': 5, 'name': 'tongueLeft'},
        'tongueRight': {'index': 6, 'name': 'tongueRight'},
        'tongueWide': {'index': 7, 'name': 'tongueWide'},
        'tongueThin': {'index': 8, 'name': 'tongueThin'},
        'tongueCurlUp': {'index': 9, 'name': 'tongueCurlUp'},
        'tongueCurlDown': {'index': 10, 'name': 'tongueCurlDown'},
    }
}
