ARKIT = {
    'Data': {
        'eyeBlinkLeft': {'index': 0, 'name': 'eyeBlinkLeft'},
        'eyeLookDownLeft': {'index': 1, 'name': 'eyeLookDownLeft'},
        'eyeLookInLeft': {'index': 2, 'name': 'eyeLookInLeft'},
        'eyeLookOutLeft': {'index': 3, 'name': 'eyeLookOutLeft'},
        'eyeLookUpLeft': {'index': 4, 'name': 'eyeLookUpLeft'},
        'eyeSquintLeft': {'index': 5, 'name': 'eyeSquintLeft'},
        'eyeWideLeft': {'index': 6, 'name': 'eyeWideLeft'},
        'eyeBlinkRight': {'index': 7, 'name': 'eyeBlinkRight'},
        'eyeLookDownRight': {'index': 8, 'name': 'eyeLookDownRight'},
        'eyeLookInRight': {'index': 9, 'name': 'eyeLookInRight'},
        'eyeLookOutRight': {'index': 10, 'name': 'eyeLookOutRight'},
        'eyeLookUpRight': {'index': 11, 'name': 'eyeLookUpRight'},
        'eyeSquintRight': {'index': 12, 'name': 'eyeSquintRight'},
        'eyeWideRight': {'index': 13, 'name': 'eyeWideRight'},
        'jawForward': {'index': 14, 'name': 'jawForward'},
        'jawLeft': {'index': 15, 'name': 'jawLeft'},
        'jawRight': {'index': 16, 'name': 'jawRight'},
        'jawOpen': {'index': 17, 'name': 'jawOpen'},
        'mouthClose': {'index': 18, 'name': 'mouthClose'},
        'mouthFunnel': {'index': 19, 'name': 'mouthFunnel'},
        'mouthPucker': {'index': 20, 'name': 'mouthPucker'},
        'mouthRight': {'index': 21, 'name': 'mouthRight'},
        'mouthLeft': {'index': 22, 'name': 'mouthLeft'},
        'mouthSmileLeft': {'index': 23, 'name': 'mouthSmileLeft'},
        'mouthSmileRight': {'index': 24, 'name': 'mouthSmileRight'},
        'mouthFrownRight': {'index': 25, 'name': 'mouthFrownRight'},
        'mouthFrownLeft': {'index': 26, 'name': 'mouthFrownLeft'},
        'mouthDimpleLeft': {'index': 27, 'name': 'mouthDimpleLeft'},
        'mouthDimpleRight': {'index': 28, 'name': 'mouthDimpleRight'},
        'mouthStretchLeft': {'index': 29, 'name': 'mouthStretchLeft'},
        'mouthStretchRight': {'index': 30, 'name': 'mouthStretchRight'},
        'mouthRollLower': {'index': 31, 'name': 'mouthRollLower'},
        'mouthRollUpper': {'index': 32, 'name': 'mouthRollUpper'},
        'mouthShrugLower': {'index': 33, 'name': 'mouthShrugLower'},
        'mouthShrugUpper': {'index': 34, 'name': 'mouthShrugUpper'},
        'mouthPressLeft': {'index': 35, 'name': 'mouthPressLeft'},
        'mouthPressRight': {'index': 36, 'name': 'mouthPressRight'},
        'mouthLowerDownLeft': {'index': 37, 'name': 'mouthLowerDownLeft'},
        'mouthLowerDownRight': {'index': 38, 'name': 'mouthLowerDownRight'},
        'mouthUpperUpLeft': {'index': 39, 'name': 'mouthUpperUpLeft'},
        'mouthUpperUpRight': {'index': 40, 'name': 'mouthUpperUpRight'},
        'browDownLeft': {'index': 41, 'name': 'browDownLeft'},
        'browDownRight': {'index': 42, 'name': 'browDownRight'},
        'browInnerUp': {'index': 43, 'name': 'browInnerUp'},
        'browOuterUpLeft': {'index': 44, 'name': 'browOuterUpLeft'},
        'browOuterUpRight': {'index': 45, 'name': 'browOuterUpRight'},
        'cheekPuff': {'index': 46, 'name': 'cheekPuff'},
        'cheekSquintLeft': {'index': 47, 'name': 'cheekSquintLeft'},
        'cheekSquintRight': {'index': 48, 'name': 'cheekSquintRight'},
        'noseSneerLeft': {'index': 49, 'name': 'noseSneerLeft'},
        'noseSneerRight': {'index': 50, 'name': 'noseSneerRight'},
        'tongueOut': {'index': 51, 'name': 'tongueOut'},
    }
}
FACECAP = {
    'Data': {
        'browInnerUp': {'index': 0, 'name': 'browInnerUp'},
        'browDownLeft': {'index': 1, 'name': 'browDown_L'},
        'browDownRight': {'index': 2, 'name': 'browDown_R'},
        'browOuterUpLeft': {'index': 3, 'name': 'browOuterUp_L'},
        'browOuterUpRight': {'index': 4, 'name': 'browOuterUp_R'},
        'eyeLookUpLeft': {'index': 5, 'name': 'eyeLookUp_L'},
        'eyeLookUpRight': {'index': 6, 'name': 'eyeLookUp_R'},
        'eyeLookDownLeft': {'index': 7, 'name': 'eyeLookDown_L'},
        'eyeLookDownRight': {'index': 8, 'name': 'eyeLookDown_R'},
        'eyeLookInLeft': {'index': 9, 'name': 'eyeLookIn_L'},
        'eyeLookInRight': {'index': 10, 'name': 'eyeLookIn_R'},
        'eyeLookOutLeft': {'index': 11, 'name': 'eyeLookOut_L'},
        'eyeLookOutRight': {'index': 12, 'name': 'eyeLookOut_R'},
        'eyeBlinkLeft': {'index': 13, 'name': 'eyeBlink_L'},
        'eyeBlinkRight': {'index': 14, 'name': 'eyeBlink_R'},
        'eyeSquintLeft': {'index': 15, 'name': 'eyeSquint_L'},
        'eyeSquintRight': {'index': 16, 'name': 'eyeSquint_R'},
        'eyeWideLeft': {'index': 17, 'name': 'eyeWide_L'},
        'eyeWideRight': {'index': 18, 'name': 'eyeWide_R'},
        'cheekPuff': {'index': 19, 'name': 'cheekPuff'},
        'cheekSquintLeft': {'index': 20, 'name': 'cheekSquint_L'},
        'cheekSquintRight': {'index': 21, 'name': 'cheekSquint_R'},
        'noseSneerLeft': {'index': 22, 'name': 'noseSneer_L'},
        'noseSneerRight': {'index': 23, 'name': 'noseSneer_R'},
        'jawOpen': {'index': 24, 'name': 'jawOpen'},
        'jawForward': {'index': 25, 'name': 'jawForward'},
        'jawLeft': {'index': 26, 'name': 'jawLeft'},
        'jawRight': {'index': 27, 'name': 'jawRight'},
        'mouthFunnel': {'index': 28, 'name': 'mouthFunnel'},
        'mouthPucker': {'index': 29, 'name': 'mouthPucker'},
        'mouthLeft': {'index': 30, 'name': 'mouthLeft'},
        'mouthRight': {'index': 31, 'name': 'mouthRight'},
        'mouthRollUpper': {'index': 32, 'name': 'mouthRollUpper'},
        'mouthRollLower': {'index': 33, 'name': 'mouthRollLower'},
        'mouthShrugUpper': {'index': 34, 'name': 'mouthShrugUpper'},
        'mouthShrugLower': {'index': 35, 'name': 'mouthShrugLower'},
        'mouthClose': {'index': 36, 'name': 'mouthClose'},
        'mouthSmileLeft': {'index': 37, 'name': 'mouthSmile_L'},
        'mouthSmileRight': {'index': 38, 'name': 'mouthSmile_R'},
        'mouthFrownLeft': {'index': 39, 'name': 'mouthFrown_L'},
        'mouthFrownRight': {'index': 40, 'name': 'mouthFrown_R'},
        'mouthDimpleLeft': {'index': 41, 'name': 'mouthDimple_L'},
        'mouthDimpleRight': {'index': 42, 'name': 'mouthDimple_R'},
        'mouthUpperUpLeft': {'index': 43, 'name': 'mouthUpperUp_L'},
        'mouthUpperUpRight': {'index': 44, 'name': 'mouthUpperUp_R'},
        'mouthLowerDownLeft': {'index': 45, 'name': 'mouthLowerDown_L'},
        'mouthLowerDownRight': {'index': 46, 'name': 'mouthLowerDown_R'},
        'mouthPressLeft': {'index': 47, 'name': 'mouthPress_L'},
        'mouthPressRight': {'index': 48, 'name': 'mouthPress_R'},
        'mouthStretchLeft': {'index': 49, 'name': 'mouthStretch_L'},
        'mouthStretchRight': {'index': 50, 'name': 'mouthStretch_R'},
        'tongueOut': {'index': 51, 'name': 'tongueOut'},
    },
}
EPIC = {
    'Data': {
        'eyeBlinkRight': {'index': 0, 'name': 'eyeBlinkRight'},
        'eyeLookDownRight': {'index': 1, 'name': 'eyeLookDownRight'},
        'eyeLookInRight': {'index': 2, 'name': 'eyeLookInRight'},
        'eyeLookOutRight': {'index': 3, 'name': 'eyeLookOutRight'},
        'eyeLookUpRight': {'index': 4, 'name': 'eyeLookUpRight'},
        'eyeSquintRight': {'index': 5, 'name': 'eyeSquintRight'},
        'eyeWideRight': {'index': 6, 'name': 'eyeWideRight'},
        'eyeBlinkLeft': {'index': 7, 'name': 'eyeBlinkLeft'},
        'eyeLookDownLeft': {'index': 8, 'name': 'eyeLookDownLeft'},
        'eyeLookInLeft': {'index': 9, 'name': 'eyeLookInLeft'},
        'eyeLookOutLeft': {'index': 10, 'name': 'eyeLookOutLeft'},
        'eyeLookUpLeft': {'index': 11, 'name': 'eyeLookUpLeft'},
        'eyeSquintLeft': {'index': 12, 'name': 'eyeSquintLeft'},
        'eyeWideLeft': {'index': 13, 'name': 'eyeWideLeft'},
        'jawForward': {'index': 14, 'name': 'jawForward'},
        'jawRight': {'index': 15, 'name': 'jawRight'},
        'jawLeft': {'index': 16, 'name': 'jawLeft'},
        'jawOpen': {'index': 17, 'name': 'jawOpen'},
        'mouthClose': {'index': 18, 'name': 'mouthClose'},
        'mouthFunnel': {'index': 19, 'name': 'mouthFunnel'},
        'mouthPucker': {'index': 20, 'name': 'mouthPucker'},
        'mouthRight': {'index': 21, 'name': 'mouthRight'},
        'mouthLeft': {'index': 22, 'name': 'mouthLeft'},
        'mouthSmileRight': {'index': 23, 'name': 'mouthSmileRight'},
        'mouthSmileLeft': {'index': 24, 'name': 'mouthSmileLeft'},
        'mouthFrownRight': {'index': 25, 'name': 'mouthFrownRight'},
        'mouthFrownLeft': {'index': 26, 'name': 'mouthFrownLeft'},
        'mouthDimpleRight': {'index': 27, 'name': 'mouthDimpleRight'},
        'mouthDimpleLeft': {'index': 28, 'name': 'mouthDimpleLeft'},
        'mouthStretchRight': {'index': 29, 'name': 'mouthStretchRight'},
        'mouthStretchLeft': {'index': 30, 'name': 'mouthStretchLeft'},
        'mouthRollLower': {'index': 31, 'name': 'mouthRollLower'},
        'mouthRollUpper': {'index': 32, 'name': 'mouthRollUpper'},
        'mouthShrugLower': {'index': 33, 'name': 'mouthShrugLower'},
        'mouthShrugUpper': {'index': 34, 'name': 'mouthShrugUpper'},
        'mouthPressRight': {'index': 35, 'name': 'mouthPressRight'},
        'mouthPressLeft': {'index': 36, 'name': 'mouthPressLeft'},
        'mouthLowerDownRight': {'index': 37, 'name': 'mouthLowerDownRight'},
        'mouthLowerDownLeft': {'index': 38, 'name': 'mouthLowerDownLeft'},
        'mouthUpperUpRight': {'index': 39, 'name': 'mouthUpperUpRight'},
        'mouthUpperUpLeft': {'index': 40, 'name': 'mouthUpperUpLeft'},
        'browDownRight': {'index': 41, 'name': 'browDownRight'},
        'browDownLeft': {'index': 42, 'name': 'browDownLeft'},
        'browInnerUp': {'index': 43, 'name': 'browInnerUp'},
        'browOuterUpRight': {'index': 44, 'name': 'browOuterUpRight'},
        'browOuterUpLeft': {'index': 45, 'name': 'browOuterUpLeft'},
        'cheekPuff': {'index': 46, 'name': 'cheekPuff'},
        'cheekSquintRight': {'index': 47, 'name': 'cheekSquintRight'},
        'cheekSquintLeft': {'index': 48, 'name': 'cheekSquintLeft'},
        'noseSneerRight': {'index': 49, 'name': 'noseSneerRight'},
        'noseSneerLeft': {'index': 50, 'name': 'noseSneerLeft'},
        'tongueOut': {'index': 51, 'name': 'tongueOut'},
    },
}


FACE_REGIONS_BASE = {
    'Eyes': [
        'eyeBlinkLeft',
        'eyeLookDownLeft',
        'eyeLookInLeft',
        'eyeLookOutLeft',
        'eyeLookUpLeft',
        'eyeSquintLeft',
        'eyeWideLeft',
        'eyeBlinkRight',
        'eyeLookDownRight',
        'eyeLookInRight',
        'eyeLookOutRight',
        'eyeLookUpRight',
        'eyeSquintRight',
        'eyeWideRight',
    ],
    'Brows': [
        'browDownLeft',
        'browDownRight',
        'browInnerUp',
        'browOuterUpLeft',
        'browOuterUpRight',
    ],
    'Cheeks': [
        'cheekPuff',
        'cheekSquintLeft',
        'cheekSquintRight',
    ],
    'Nose': [
        'noseSneerLeft',
        'noseSneerRight',
    ],
    'Mouth': [
        'jawForward',
        'jawLeft',
        'jawRight',
        'jawOpen',
        'mouthClose',
        'mouthFunnel',
        'mouthPucker',
        'mouthRight',
        'mouthLeft',
        'mouthSmileLeft',
        'mouthSmileRight',
        'mouthFrownRight',
        'mouthFrownLeft',
        'mouthDimpleLeft',
        'mouthDimpleRight',
        'mouthStretchLeft',
        'mouthStretchRight',
        'mouthRollLower',
        'mouthRollUpper',
        'mouthShrugLower',
        'mouthShrugUpper',
        'mouthPressLeft',
        'mouthPressRight',
        'mouthLowerDownLeft',
        'mouthLowerDownRight',
        'mouthUpperUpLeft',
        'mouthUpperUpRight',
    ],
    'Tongue': [
        'TongueOut',
    ],
}
